### ISSUE TITLE
Xamarin Archive Step Failed - Unable to locate NuGet.exe

### ISSUE THREAD

**Issue by hvaughan3** [bitrise-steplib/steps-xamarin-archive#19]
Workflow has been working fine when building a Xamarin Forms project (other than being unable to get the build times below the timeout cut off).

Just now switched over to using the **Xamarin Archive** step using xbuild

 and the step is failing when attempting to build the Xamarin.iOS and the Xamarin.Android projects.

It fails with the error:

> /Users/vagrant/git/.nuget/NuGet.targets: error : Unable to locate '/Users/vagrant/git.nuget/NuGet.exe'

This happens even though the **NuGet Restore** step just before the **Xamarin Archive** step completes successfully.

Full log output (with certain step outputs deleted and the project name changed):
[04f526cecd3b80b4.txt](https://github.com/bitrise-steplib/steps-xamarin-archive/files/955889/04f526cecd3b80b4.txt)

**Comment by godrei** [comment]
Hi @hvaughan3 ,
thanks for the report, we will have a look ASAP!

**Comment by trapacska** [comment]
Hi @hvaughan3 !

From the log it seems like this issue is coming from Xamarin. It is related to a wrong nugget path settings in your project, or maybe your nuget.exe is gitignored, etc...

The difference between our Nuget Restore step and the build in Xamarin NuGet restore is that our step uses a different path `/Library/Frameworks/Mono.framework/Versions/Current/bin/nuget` than the build in one, which is looking for .nuget.

At first I would recommend to read more here: http://stackoverflow.com/questions/13932154/unable-to-locate-nuget-exe-when-building-webservice-on-appharbor/18517069
They are discussing multiple possible issues.

The most interesting part is why the log says:
`Unable to locate '/Users/vagrant/git.nuget/NuGet.exe'`
as it should be:
`Unable to locate '/Users/vagrant/git/.nuget/NuGet.exe'`

Is it possible that the path is not configured properly in your nuget.Target file?
 
Please let me know if this resolves your issue.

**Comment by hvaughan3** [comment]
@trapacska Really appreciate you looking into this. So looking into my **NuGet.targets** file, I found where it tries to launch **nuget.exe** when not running on a windows machine:

```
     <PropertyGroup Condition=" '$(OS)' != 'Windows_NT'">
         <!-- We need to launch nuget.exe with the mono command if we're not on windows -->
         <NuGetToolsPath>$(SolutionDir).nuget</NuGetToolsPath>
     </PropertyGroup>
```

I just tried adding a `\` between the two folders and it worked!! The strange thing is that I have never touched the **NuGet.targets** file myself so not sure what could have changed to cause this. So that section above became:

```
     <PropertyGroup Condition=" '$(OS)' != 'Windows_NT'">
         <!-- We need to launch nuget.exe with the mono command if we're not on windows -->
         <NuGetToolsPath>$(SolutionDir)\.nuget</NuGetToolsPath>
     </PropertyGroup>
```

Also, I have not actually tried testing any NuGet related functionality within Visual Studio after making this change so it could have messed something up there. Will definitely post a new comment to this thread if that happens.

**Comment by trapacska** [comment]
@hvaughan3 thank you for the feedback. Happy to hear it solved the issue. 🚀🎉

I think this can be because of MS vs unix system difference, maybe another version of the IDE already solves this. Not sure about this 😊

Feel free to reopen this issue if you get an issue again! 😉
